[package]
name = "reserv"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
sqlx = { version = "0.8.3", features = [
    "runtime-tokio",
    "tls-rustls-ring",
    "postgres",
    "time",
    "uuid",
] }
tokio = { version = "1.43.0", features = ["rt-multi-thread", "macros"] }
