services:
  postgres:
    image: postgres
    container_name: pg_tests
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=testdb
    ports:
      - "5432:5432"
