services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=examples
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    expose:
      - "5432"
    ports:
      - "5432:5432"
