[package]
name = "crates"
version = "0.1.0"
edition = "2024"

[[example]]
name = "tracing"
test = true

[dependencies]
sqlx = "0.8.3"
tokio = { version = "1.44.2", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
